Create database sales_data_analysis;

USE sales_data_analysis;
select * from customers;
select * from Products;
select * from Orders;
select * from Orders_Item;
select count(*) from customers;

-- Questions?
-- 1. 	Display all customers from Pune?
select * from customers
where city  = "Pune";

-- 2.	List all products in the Electronics category.
select * from products
where category = "Electronics";
-- 3.	Find all orders with status = 'Completed'.
select * from Orders
where Status = "Completed";

-- 4.	Show top 10 most expensive products.
select * from Products
order by Price desc limit 10;

-- 5.	Find customers whose email is missing. -----???
Select * from customers
where email is null;
SELECT * FROM customers
WHERE email like " ";
select * from customers;
-- 6.	Find total sales amount (sum of total_amount). 
Select sum(total_amount) as Total_Sales from Orders_Item;

-- 7.	Find average product price by category.
Select category, avg(Price) as Avg from Products
group by category;
 
-- 8.	Count number of orders for each status.
select status,Count(order_id) from orders
group by status;

-- 9.	Find total quantity sold for each product.
select product_id, sum(quantity) as Sold_Qty from orders_item
group by product_id;

-- 10.	Find maximum and minimum order amount.
select max(Total_amount) as Max_Amt, min(total_amount) as Min_amt from orders_item;

-- 11.	Display order_id, customer_name, order_date, and status.
select order_id, Customer_name,Order_date, Status from customers c 
join orders o 
on c.customer_id = o.customer_id;

-- 12.	Show customer_name, product_name, quantity, and total_amount for each sale?
select customer_name, Product_name, quantity, Total_amount from customers c 
inner join orders o 
on c.customer_id = o.customer_id 
join orders_item oi 
on o.order_id = oi.order_id
right join products p 
on p.product_id = oi.product_id;

-- 13.	Find total sales done by each customer. 
select c.customer_id, sum(total_amount) as Total_sales from customers c 
join orders o 
on c.customer_id = o.customer_id
join orders_item oi 
on o.order_id = oi.order_id
group by c.customer_id;


   -- 14.	Find total revenue generated by each category.
   select Category,sum(price* quantity) as Revenue from products p 
   left join orders_item oi
   on p.product_id = oi.Product_id
   group by category;
   
   -- 15.	Find customers who have placed more than 3 orders. 
   select customer_name, quantity from Customers c 
  right join orders o 
   on c.customer_id = o.customer_id
  inner join orders_item oi 
   on o.order_id = oi.order_id
   having quantity > 3;
   
   -- 16.	Find products whose total sales amount is greater than 1,00,000.
   select Product_Id, Total_amount from orders_item
   having total_amount > 100000;
   
   -- 17.	Show city-wise total sales.
   select city, total_amount from customers c 
   left join orders o 
   on c.Customer_id = o.customer_id
   left join orders_item oi 
   on o.order_id = oi.order_id;
   
-- 18.	Replace missing discount values with 0 and calculate final amount. 
Update orders_item
set discount = 0
where discount = " ";
select * from orders_item;
SELECT order_item_id,Total_amount, total_amount - discount as Final_amt from orders_item; 

    
-- 19.	Show order status as:
	-- ‘Done’ for Completed
-- ‘Waiting’ for Pending
-- ‘Rejected’ for Cancelled
select status, 
case 
when status = "Completed" then "Done"
when status = "Pending" then "Waiting" 
else "Rejected"
end as Order_Status from Orders;

-- 20.	Find customers who have never placed any order. 
Select * from orders
-- where customer_id = ( select customer_id from orders 
where order_id is null);

